### ISSUE TITLE
Question: Custom Error Types

### ISSUE THREAD

**Issue by ceckoslab** [chdb-io/chdb-node#19]
Hello @auxten as far as I understand we get the default Error type when there is an error in chdb.

Recently I faced a situation where I got a message with the following message:
```
Code: 57. DB::Exception: Directory for table data data/default/testtable/ already exists. (TABLE_ALREADY_EXISTS)
```

Currently I don't have an easy way to know if the error was because I was trying to create already existing table. I could figure out this if I was doing string search for `TABLE_ALREADY_EXISTS`.

I suppose that it's a lot of work but what do you think about the idea to have something like this in the near future:

```
try {
  session.query("CREATE TABLE testtable (id UInt32) ENGINE = MergeTree() ORDER BY id;");
} catch (err) {
  if (err instanceof TableAlreadyExists) {
    // Do something
  } else if (err instanceof SyntaxError) {
    // Do something
  } else {
    throw err; // unknown error, re-throw 
  }
}
```

**Comment by auxten** [comment]
There are more than 700 error types in ClickHouse engine.
https://github.com/chdb-io/chdb/blob/fix-global-import/src/Common/ErrorCodes.cpp#L16

So, I think just make it simple string is good for maintenance.

**Comment by ceckoslab** [comment]
I see @auxten 

This probably doesn't bring much value to the project at the moment.

However, out of curiocity I have the following question: Wouldn't it be possible to have CHDB specific errors in an automated way as here we can see a patter how the ERROR CODES are being defined: https://github.com/chdb-io/chdb/blob/fix-global-import/src/Common/ErrorCodes.cpp#L16

```
...
    M(0, OK) \
    M(1, UNSUPPORTED_METHOD) \
    M(2, UNSUPPORTED_PARAMETER) \
    M(3, UNEXPECTED_END_OF_FILE) \
    M(4, EXPECTED_END_OF_FILE) \
    M(6, CANNOT_PARSE_TEXT) \
    M(7, INCORRECT_NUMBER_OF_COLUMNS) \
    M(8, THERE_IS_NO_COLUMN) \
    M(9, SIZES_OF_COLUMNS_DOESNT_MATCH) \
    M(10, NOT_FOUND_COLUMN_IN_BLOCK) \
    M(11, POSITION_OUT_OF_BOUND) \
    M(12, PARAMETER_OUT_OF_BOUND) \
    M(13, SIZES_OF_COLUMNS_IN_TUPLE_DOESNT_MATCH) \
    M(15, DUPLICATE_COLUMN) \
    M(16, NO_SUCH_COLUMN_IN_TABLE) \
    M(19, SIZE_OF_FIXED_STRING_DOESNT_MATCH) \
    M(20, NUMBER_OF_COLUMNS_DOESNT_MATCH) \
    M(23, CANNOT_READ_FROM_ISTREAM) \
...
```

I am not a C++ expert but I suppose I could help in the future if you as a maintainer would like to have custom errors. I probably will need some guidance on the C++ side of course.
