### ISSUE TITLE
Any plan for Windows support?

### ISSUE THREAD

**Issue by stefenson** [chdb-io/chdb-node#21]
![image](https://github.com/user-attachments/assets/0915b876-6906-43c1-b56a-6816f90c2d0f)

**Comment by auxten** [comment]
ClickHouse do not support Windows. So does chDB. But chDB on WSL works perfect

**Comment by stefenson** [comment]
Oh, my bad. I forgot that Clickhouse doesn't support Windows.
OK, I will find another OLAP embedded database instead, thank you <3.
